# syntax=docker/dockerfile:1

# -------------------
# Base image
# -------------------
FROM node:22-alpine AS base
WORKDIR /app
COPY package*.json ./

# -------------------
# Development stage
# -------------------
FROM base AS dev
RUN yarn install
COPY . .
EXPOSE 3000
CMD ["yarn", "dev"]

# -------------------
# Production build stage
# -------------------
FROM base AS build
RUN yarn install --production
COPY . .
RUN yarn build

# -------------------
# Production runtime
# -------------------
FROM node:22-alpine AS prod
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
RUN yarn install --production
EXPOSE 8000
CMD ["yarn", "start"]
